jQuery(function($) {
    

    $(window).load(function() {

      function obtentores(element) {
        jQuery(element).selectize({
            options: [
              { obtentor: 'GENSUS', cultivo: "Algodon", variedad: "DP 1238 BGRR", value: "GENSUS: Algodon | DP 1238 BGRR" },
              {obtentor:'GENSUS',Cultivo: "ALGODON" , variedad: "DP 1238 BGRR" , value: "GENSUS: ALGODON | DP 1238 BGRR"},
{obtentor:'GENSUS',Cultivo: "ALGODON" , variedad: "DP 402 BG/RR" , value: "GENSUS: ALGODON | DP 402 BG/RR"},
{obtentor:'GENSUS',Cultivo: "ALGODON" , variedad: "GUARANI INTA BGRR" , value: "GENSUS: ALGODON | GUARANI INTA BGRR"},
{obtentor:'GENSUS',Cultivo: "ALGODON" , variedad: "GUAZUNCHO 2000" , value: "GENSUS: ALGODON | GUAZUNCHO 2000"},
{obtentor:'GENSUS',Cultivo: "ALGODON" , variedad: "GUAZUNCHO 4 INTA BGRR" , value: "GENSUS: ALGODON | GUAZUNCHO 4 INTA BGRR"},
{obtentor:'GENSUS',Cultivo: "ALGODON" , variedad: "NUOPAL RR" , value: "GENSUS: ALGODON | NUOPAL RR"},
{obtentor:'GENSUS',Cultivo: "ALGODON" , variedad: "NUOPAL RR" , value: "GENSUS: ALGODON | NUOPAL RR"},
{obtentor:'GENSUS',Cultivo: "ALGODON" , variedad: "PORA 3 INTA BGRR" , value: "GENSUS: ALGODON | PORA 3 INTA BGRR"},
{obtentor:'COPRA',Cultivo: "ARROZ" , variedad: "IRGA 424" , value: "COPRA: ARROZ | IRGA 424"},
{obtentor:'PILAGA',Cultivo: "ARROZ" , variedad: "ITA CAABO 107" , value: "PILAGA: ARROZ | ITA CAABO 107"},
{obtentor:'PILAGA',Cultivo: "ARROZ" , variedad: "ITA CAABO 109" , value: "PILAGA: ARROZ | ITA CAABO 109"},
{obtentor:'PILAGA',Cultivo: "ARROZ" , variedad: "ITA CAABO 110" , value: "PILAGA: ARROZ | ITA CAABO 110"},
{obtentor:'PILAGA',Cultivo: "ARROZ" , variedad: "SCS121 CL" , value: "PILAGA: ARROZ | SCS121 CL"},
{obtentor:'ARVES',Cultivo: "ARVEJA" , variedad: "BICENTENARIO" , value: "ARVES: ARVEJA | BICENTENARIO"},
{obtentor:'ARVES',Cultivo: "ARVEJA" , variedad: "MANANTIALES" , value: "ARVES: ARVEJA | MANANTIALES"},
{obtentor:'ARVES',Cultivo: "ARVEJA" , variedad: "PAMPA" , value: "ARVES: ARVEJA | PAMPA"},
{obtentor:'ARVES',Cultivo: "ARVEJA" , variedad: "ROSITA" , value: "ARVES: ARVEJA | ROSITA"},
{obtentor:'BIOSEMINIS',Cultivo: "ARVEJA" , variedad: "AVIRON" , value: "BIOSEMINIS: ARVEJA | AVIRON"},
{obtentor:'BIOSEMINIS',Cultivo: "ARVEJA" , variedad: "BALLTRAP" , value: "BIOSEMINIS: ARVEJA | BALLTRAP"},
{obtentor:'BIOSEMINIS',Cultivo: "ARVEJA" , variedad: "CURLING" , value: "BIOSEMINIS: ARVEJA | CURLING"},
{obtentor:'BIOSEMINIS',Cultivo: "ARVEJA" , variedad: "REUSSITE" , value: "BIOSEMINIS: ARVEJA | REUSSITE"},
{obtentor:'BIOSEMINIS',Cultivo: "ARVEJA" , variedad: "YAMS" , value: "BIOSEMINIS: ARVEJA | YAMS"},
{obtentor:'SURSEM',Cultivo: "ARVEJA" , variedad: "AVENGER" , value: "SURSEM: ARVEJA | AVENGER"},
{obtentor:'SURSEM',Cultivo: "ARVEJA" , variedad: "KINGFISHER" , value: "SURSEM: ARVEJA | KINGFISHER"},
{obtentor:'SURSEM',Cultivo: "ARVEJA" , variedad: "SHAMROCK" , value: "SURSEM: ARVEJA | SHAMROCK"},
{obtentor:'AZCUE CASTRO',Cultivo: "AVENA" , variedad: "ELIZABET INTA" , value: "AZCUE CASTRO: AVENA | ELIZABET INTA"},
{obtentor:'BARROW',Cultivo: "AVENA" , variedad: "BONAERENSE INTA SUREÑA" , value: "BARROW: AVENA | BONAERENSE INTA SUREÑA"},
{obtentor:'A.C.A.',Cultivo: "CEBADA" , variedad: "FATIMA" , value: "A.C.A.: CEBADA | FATIMA"},
{obtentor:'A.C.A.',Cultivo: "CEBADA" , variedad: "LG SINFONIA" , value: "A.C.A.: CEBADA | LG SINFONIA"},
{obtentor:'A.C.A.',Cultivo: "CEBADA" , variedad: "TRAVELER" , value: "A.C.A.: CEBADA | TRAVELER"},
{obtentor:'ACOPIO AREQUITO',Cultivo: "CEBADA" , variedad: "INTA 7302" , value: "ACOPIO AREQUITO: CEBADA | INTA 7302"},
{obtentor:'ACOPIO AREQUITO',Cultivo: "CEBADA" , variedad: "SARA INTA" , value: "ACOPIO AREQUITO: CEBADA | SARA INTA"},
{obtentor:'BUCK',Cultivo: "CEBADA" , variedad: "BUCK 316" , value: "BUCK: CEBADA | BUCK 316"},
{obtentor:'NIDERA',Cultivo: "CEBADA" , variedad: "EXPLORER" , value: "NIDERA: CEBADA | EXPLORER"},
{obtentor:'QUILMES',Cultivo: "CEBADA" , variedad: "ALHUE" , value: "QUILMES: CEBADA | ALHUE"},
{obtentor:'QUILMES',Cultivo: "CEBADA" , variedad: "DANIELLE" , value: "QUILMES: CEBADA | DANIELLE"},
{obtentor:'QUILMES',Cultivo: "CEBADA" , variedad: "MONTOYA" , value: "QUILMES: CEBADA | MONTOYA"},
{obtentor:'QUILMES',Cultivo: "CEBADA" , variedad: "YANARA" , value: "QUILMES: CEBADA | YANARA"},
{obtentor:'SURSEM',Cultivo: "CEBADA" , variedad: "CLE 232" , value: "SURSEM: CEBADA | CLE 232"},
{obtentor:'SURSEM',Cultivo: "CEBADA" , variedad: "LG ANDANTE" , value: "SURSEM: CEBADA | LG ANDANTE"},
{obtentor:'SURSEM',Cultivo: "CEBADA" , variedad: "LG ZODIAC" , value: "SURSEM: CEBADA | LG ZODIAC"},
{obtentor:'SURSEM',Cultivo: "CEBADA" , variedad: "OVERTURE" , value: "SURSEM: CEBADA | OVERTURE"},
{obtentor:'SURSEM',Cultivo: "CEBADA" , variedad: "RUBIA 235" , value: "SURSEM: CEBADA | RUBIA 235"},
{obtentor:'HZPC AMERICA',Cultivo: "PAPA" , variedad: "INNOVATOR" , value: "HZPC AMERICA: PAPA | INNOVATOR"},
{obtentor:'HZPC AMERICA',Cultivo: "PAPA" , variedad: "IVORY RUSSET" , value: "HZPC AMERICA: PAPA | IVORY RUSSET"},
{obtentor:'HZPC AMERICA',Cultivo: "PAPA" , variedad: "SAGITTA" , value: "HZPC AMERICA: PAPA | SAGITTA"},
{obtentor:'HZPC AMERICA',Cultivo: "PAPA" , variedad: "TAURUS" , value: "HZPC AMERICA: PAPA | TAURUS"},
{obtentor:'HZPC AMERICA',Cultivo: "PAPA" , variedad: "VOYAGER" , value: "HZPC AMERICA: PAPA | VOYAGER"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "3535" , value: "A.C.A.: SOJA | 3535"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "3737 GRTS" , value: "A.C.A.: SOJA | 3737 GRTS"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "3838" , value: "A.C.A.: SOJA | 3838"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "3939" , value: "A.C.A.: SOJA | 3939"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "42A21" , value: "A.C.A.: SOJA | 42A21"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "4521" , value: "A.C.A.: SOJA | 4521"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "4660" , value: "A.C.A.: SOJA | 4660"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "4949 IPRO" , value: "A.C.A.: SOJA | 4949 IPRO"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "5020 IPRO" , value: "A.C.A.: SOJA | 5020 IPRO"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "5350" , value: "A.C.A.: SOJA | 5350"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "5785" , value: "A.C.A.: SOJA | 5785"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "5814IPRO" , value: "A.C.A.: SOJA | 5814IPRO"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "5825IPRO" , value: "A.C.A.: SOJA | 5825IPRO"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "6513 IPRO" , value: "A.C.A.: SOJA | 6513 IPRO"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "6720IPRO" , value: "A.C.A.: SOJA | 6720IPRO"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "7890 IPRO" , value: "A.C.A.: SOJA | 7890 IPRO"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "ACA 41A20" , value: "A.C.A.: SOJA | ACA 41A20"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "INTA MJ42-STS" , value: "A.C.A.: SOJA | INTA MJ42-STS"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "VC 4220 IPRO" , value: "A.C.A.: SOJA | VC 4220 IPRO"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "VC 4550" , value: "A.C.A.: SOJA | VC 4550"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "VC 4990" , value: "A.C.A.: SOJA | VC 4990"},
{obtentor:'A.C.A.',Cultivo: "SOJA" , variedad: "VC 8080 IPRO" , value: "A.C.A.: SOJA | VC 8080 IPRO"},
{obtentor:'AGD',Cultivo: "SOJA" , variedad: "CQ 4.55" , value: "AGD: SOJA | CQ 4.55"},
{obtentor:'AGD',Cultivo: "SOJA" , variedad: "CQ 4.90" , value: "AGD: SOJA | CQ 4.90"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 390" , value: "AGRISEED: SOJA | DALIA 390"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 455" , value: "AGRISEED: SOJA | DALIA 455"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 458" , value: "AGRISEED: SOJA | DALIA 458"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 465" , value: "AGRISEED: SOJA | DALIA 465"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 485" , value: "AGRISEED: SOJA | DALIA 485"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 490" , value: "AGRISEED: SOJA | DALIA 490"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 500" , value: "AGRISEED: SOJA | DALIA 500"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 550" , value: "AGRISEED: SOJA | DALIA 550"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 580" , value: "AGRISEED: SOJA | DALIA 580"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 610" , value: "AGRISEED: SOJA | DALIA 610"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 620" , value: "AGRISEED: SOJA | DALIA 620"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 680" , value: "AGRISEED: SOJA | DALIA 680"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 700" , value: "AGRISEED: SOJA | DALIA 700"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 740" , value: "AGRISEED: SOJA | DALIA 740"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 750" , value: "AGRISEED: SOJA | DALIA 750"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 780" , value: "AGRISEED: SOJA | DALIA 780"},
{obtentor:'AGRISEED',Cultivo: "SOJA" , variedad: "DALIA 810" , value: "AGRISEED: SOJA | DALIA 810"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "3806IPRO" , value: "ASGROW: SOJA | 3806IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "3920IPRO" , value: "ASGROW: SOJA | 3920IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "4320IPRO" , value: "ASGROW: SOJA | 4320IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "4326 IPRO" , value: "ASGROW: SOJA | 4326 IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "4610IPRO" , value: "ASGROW: SOJA | 4610IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "4736 IPRO" , value: "ASGROW: SOJA | 4736 IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "4914 IPRO" , value: "ASGROW: SOJA | 4914 IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "4927IPRO" , value: "ASGROW: SOJA | 4927IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "5021IPRO" , value: "ASGROW: SOJA | 5021IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "5714 IPRO" , value: "ASGROW: SOJA | 5714 IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "5815IPRO" , value: "ASGROW: SOJA | 5815IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "5920IPRO" , value: "ASGROW: SOJA | 5920IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "6211 IPRO" , value: "ASGROW: SOJA | 6211 IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "6320IPRO" , value: "ASGROW: SOJA | 6320IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "7720IPRO" , value: "ASGROW: SOJA | 7720IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "M5410 IPRO" , value: "ASGROW: SOJA | M5410 IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "M6210 IPRO" , value: "ASGROW: SOJA | M6210 IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "M6410 IPRO" , value: "ASGROW: SOJA | M6410 IPRO"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "T 2137" , value: "ASGROW: SOJA | T 2137"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "T 2142" , value: "ASGROW: SOJA | T 2142"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "T 2148" , value: "ASGROW: SOJA | T 2148"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "T 2246" , value: "ASGROW: SOJA | T 2246"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "T 2249" , value: "ASGROW: SOJA | T 2249"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "T 2259" , value: "ASGROW: SOJA | T 2259"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "T 2266" , value: "ASGROW: SOJA | T 2266"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2044" , value: "ASGROW: SOJA | TJS 2044"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2049" , value: "ASGROW: SOJA | TJS 2049"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2055" , value: "ASGROW: SOJA | TJS 2055"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2070" , value: "ASGROW: SOJA | TJS 2070"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2136 R" , value: "ASGROW: SOJA | TJS 2136 R"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2138 R" , value: "ASGROW: SOJA | TJS 2138 R"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2139 R" , value: "ASGROW: SOJA | TJS 2139 R"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2145 R" , value: "ASGROW: SOJA | TJS 2145 R"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2156 R" , value: "ASGROW: SOJA | TJS 2156 R"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2158IR" , value: "ASGROW: SOJA | TJS 2158IR"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2162 IR" , value: "ASGROW: SOJA | TJS 2162 IR"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2164 R" , value: "ASGROW: SOJA | TJS 2164 R"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2165 R" , value: "ASGROW: SOJA | TJS 2165 R"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2167 R" , value: "ASGROW: SOJA | TJS 2167 R"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2170 R" , value: "ASGROW: SOJA | TJS 2170 R"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2171 IR" , value: "ASGROW: SOJA | TJS 2171 IR"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2175R" , value: "ASGROW: SOJA | TJS 2175R"},
{obtentor:'ASGROW',Cultivo: "SOJA" , variedad: "TJS 2178 R" , value: "ASGROW: SOJA | TJS 2178 R"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "B 4.70" , value: "BIOCERES: SOJA | B 4.70"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIO 3.5" , value: "BIOCERES: SOJA | BIO 3.5"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIO 3.80" , value: "BIOCERES: SOJA | BIO 3.80"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIO 3.9" , value: "BIOCERES: SOJA | BIO 3.9"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIO 4.20" , value: "BIOCERES: SOJA | BIO 4.20"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIO 4.60" , value: "BIOCERES: SOJA | BIO 4.60"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIO 4.80" , value: "BIOCERES: SOJA | BIO 4.80"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIO 4.9" , value: "BIOCERES: SOJA | BIO 4.9"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIO 5.4" , value: "BIOCERES: SOJA | BIO 5.4"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIO 6.50" , value: "BIOCERES: SOJA | BIO 6.50"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIOCERES 3.41" , value: "BIOCERES: SOJA | BIOCERES 3.41"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIOCERES 4.11" , value: "BIOCERES: SOJA | BIOCERES 4.11"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIOCERES 4.51" , value: "BIOCERES: SOJA | BIOCERES 4.51"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIOCERES 4.91" , value: "BIOCERES: SOJA | BIOCERES 4.91"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIOCERES 5.11" , value: "BIOCERES: SOJA | BIOCERES 5.11"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIOCERES 5.21" , value: "BIOCERES: SOJA | BIOCERES 5.21"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIOCERES 5.61" , value: "BIOCERES: SOJA | BIOCERES 5.61"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIOCERES 5.91" , value: "BIOCERES: SOJA | BIOCERES 5.91"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIOCERES 5.92" , value: "BIOCERES: SOJA | BIOCERES 5.92"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIOCERES 6.21" , value: "BIOCERES: SOJA | BIOCERES 6.21"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIOCERES 6.61" , value: "BIOCERES: SOJA | BIOCERES 6.61"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "BIOSEM 8.4" , value: "BIOCERES: SOJA | BIOSEM 8.4"},
{obtentor:'BIOCERES',Cultivo: "SOJA" , variedad: "SG1059IPRO" , value: "BIOCERES: SOJA | SG1059IPRO"},
{obtentor:'CORTEVA',Cultivo: "SOJA" , variedad: "XPS 1393" , value: "CORTEVA: SOJA | XPS 1393"},
{obtentor:'CORTEVA',Cultivo: "SOJA" , variedad: "XPS 1410" , value: "CORTEVA: SOJA | XPS 1410"},
{obtentor:'CORTEVA',Cultivo: "SOJA" , variedad: "XPS 1470" , value: "CORTEVA: SOJA | XPS 1470"},
{obtentor:'CORTEVA',Cultivo: "SOJA" , variedad: "XPS 1505" , value: "CORTEVA: SOJA | XPS 1505"},
{obtentor:'CORTEVA',Cultivo: "SOJA" , variedad: "XPS 1621" , value: "CORTEVA: SOJA | XPS 1621"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "3.45 S" , value: "CREDENZ: SOJA | 3.45 S"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "3.85 S" , value: "CREDENZ: SOJA | 3.85 S"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "3.95 S" , value: "CREDENZ: SOJA | 3.95 S"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "3621" , value: "CREDENZ: SOJA | 3621"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "3906 IPRO" , value: "CREDENZ: SOJA | 3906 IPRO"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "4.25 S" , value: "CREDENZ: SOJA | 4.25 S"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "4.35-S" , value: "CREDENZ: SOJA | 4.35-S"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "4.85 S" , value: "CREDENZ: SOJA | 4.85 S"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "4.97 S" , value: "CREDENZ: SOJA | 4.97 S"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "4021" , value: "CREDENZ: SOJA | 4021"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "4306 B" , value: "CREDENZ: SOJA | 4306 B"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "4505 B" , value: "CREDENZ: SOJA | 4505 B"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "4721 STS" , value: "CREDENZ: SOJA | 4721 STS"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "4908 IPRO" , value: "CREDENZ: SOJA | 4908 IPRO"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "5.45S" , value: "CREDENZ: SOJA | 5.45S"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "5107 B" , value: "CREDENZ: SOJA | 5107 B"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "5407 IPRO" , value: "CREDENZ: SOJA | 5407 IPRO"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "5905 IPRO" , value: "CREDENZ: SOJA | 5905 IPRO"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "5907 IPRO" , value: "CREDENZ: SOJA | 5907 IPRO"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "6.41 S" , value: "CREDENZ: SOJA | 6.41 S"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "6205 B" , value: "CREDENZ: SOJA | 6205 B"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "6505 B" , value: "CREDENZ: SOJA | 6505 B"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "6806 IPRO" , value: "CREDENZ: SOJA | 6806 IPRO"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "7.55 S" , value: "CREDENZ: SOJA | 7.55 S"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "7521 IPRO" , value: "CREDENZ: SOJA | 7521 IPRO"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "7905 IPRO" , value: "CREDENZ: SOJA | 7905 IPRO"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "FN 3.60" , value: "CREDENZ: SOJA | FN 3.60"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "FN 3.90" , value: "CREDENZ: SOJA | FN 3.90"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "FN 4.10" , value: "CREDENZ: SOJA | FN 4.10"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "FN 4.50" , value: "CREDENZ: SOJA | FN 4.50"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "FN 5.55" , value: "CREDENZ: SOJA | FN 5.55"},
{obtentor:'CREDENZ',Cultivo: "SOJA" , variedad: "FN 5.75" , value: "CREDENZ: SOJA | FN 5.75"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "5351 RSF" , value: "DON MARIO: SOJA | 5351 RSF"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "53I53 RSF IPRO" , value: "DON MARIO: SOJA | 53I53 RSF IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "5958 RSF IPRO" , value: "DON MARIO: SOJA | 5958 RSF IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "60I62 RSF IPRO" , value: "DON MARIO: SOJA | 60I62 RSF IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "61I61 RSF IPRO" , value: "DON MARIO: SOJA | 61I61 RSF IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "6262 RSF IPRO" , value: "DON MARIO: SOJA | 6262 RSF IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "62R63 RSF" , value: "DON MARIO: SOJA | 62R63 RSF"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "63I64RSF IPRO" , value: "DON MARIO: SOJA | 63I64RSF IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "6563 RSF IPRO" , value: "DON MARIO: SOJA | 6563 RSF IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "66R69 RSF" , value: "DON MARIO: SOJA | 66R69 RSF"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "67I70 RSF IPRO" , value: "DON MARIO: SOJA | 67I70 RSF IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "75I75 RSF IPRO" , value: "DON MARIO: SOJA | 75I75 RSF IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "7870 RSF IPRO" , value: "DON MARIO: SOJA | 7870 RSF IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "7976 RSF IPRO" , value: "DON MARIO: SOJA | 7976 RSF IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "8075 RSF IPRO" , value: "DON MARIO: SOJA | 8075 RSF IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "8277 RSF IPRO" , value: "DON MARIO: SOJA | 8277 RSF IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "8473 RSF" , value: "DON MARIO: SOJA | 8473 RSF"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "8573 RSF IPRO" , value: "DON MARIO: SOJA | 8573 RSF IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "8576 RSF" , value: "DON MARIO: SOJA | 8576 RSF"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "ADM 3000" , value: "DON MARIO: SOJA | ADM 3000"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "ADM 3950" , value: "DON MARIO: SOJA | ADM 3950"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 2000" , value: "DON MARIO: SOJA | DON MARIO 2000"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 2200" , value: "DON MARIO: SOJA | DON MARIO 2200"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 2611" , value: "DON MARIO: SOJA | DON MARIO 2611"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 2900" , value: "DON MARIO: SOJA | DON MARIO 2900"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 3070" , value: "DON MARIO: SOJA | DON MARIO 3070"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 3100" , value: "DON MARIO: SOJA | DON MARIO 3100"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 3312 RSF" , value: "DON MARIO: SOJA | DON MARIO 3312 RSF"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 3500" , value: "DON MARIO: SOJA | DON MARIO 3500"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 3700" , value: "DON MARIO: SOJA | DON MARIO 3700"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 3810" , value: "DON MARIO: SOJA | DON MARIO 3810"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 3815 IPRO" , value: "DON MARIO: SOJA | DON MARIO 3815 IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 4014 IPRO" , value: "DON MARIO: SOJA | DON MARIO 4014 IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 40I21 IPRO" , value: "DON MARIO: SOJA | DON MARIO 40I21 IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 40R16" , value: "DON MARIO: SOJA | DON MARIO 40R16"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 40R21" , value: "DON MARIO: SOJA | DON MARIO 40R21"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 4200" , value: "DON MARIO: SOJA | DON MARIO 4200"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 4210" , value: "DON MARIO: SOJA | DON MARIO 4210"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 4212 RSF" , value: "DON MARIO: SOJA | DON MARIO 4212 RSF"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 4214" , value: "DON MARIO: SOJA | DON MARIO 4214"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 4250" , value: "DON MARIO: SOJA | DON MARIO 4250"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 4600" , value: "DON MARIO: SOJA | DON MARIO 4600"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 4612 RSF" , value: "DON MARIO: SOJA | DON MARIO 4612 RSF"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 4614 IPRO" , value: "DON MARIO: SOJA | DON MARIO 4614 IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 4615" , value: "DON MARIO: SOJA | DON MARIO 4615"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 4670" , value: "DON MARIO: SOJA | DON MARIO 4670"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 46I17 IPRO" , value: "DON MARIO: SOJA | DON MARIO 46I17 IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 46I20 IPRO" , value: "DON MARIO: SOJA | DON MARIO 46I20 IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 46R18" , value: "DON MARIO: SOJA | DON MARIO 46R18"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 4712 RSF" , value: "DON MARIO: SOJA | DON MARIO 4712 RSF"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 4870" , value: "DON MARIO: SOJA | DON MARIO 4870"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 4913 RSF" , value: "DON MARIO: SOJA | DON MARIO 4913 RSF"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 4915 IPRO" , value: "DON MARIO: SOJA | DON MARIO 4915 IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 4970" , value: "DON MARIO: SOJA | DON MARIO 4970"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 49R19" , value: "DON MARIO: SOJA | DON MARIO 49R19"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 5.1I" , value: "DON MARIO: SOJA | DON MARIO 5.1I"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 5.2I" , value: "DON MARIO: SOJA | DON MARIO 5.2I"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 5.5I" , value: "DON MARIO: SOJA | DON MARIO 5.5I"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 5.8I" , value: "DON MARIO: SOJA | DON MARIO 5.8I"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 5.9I" , value: "DON MARIO: SOJA | DON MARIO 5.9I"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 50I17 IPRO" , value: "DON MARIO: SOJA | DON MARIO 50I17 IPRO"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 52R19" , value: "DON MARIO: SOJA | DON MARIO 52R19"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 55R20" , value: "DON MARIO: SOJA | DON MARIO 55R20"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 5800" , value: "DON MARIO: SOJA | DON MARIO 5800"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 6.2I" , value: "DON MARIO: SOJA | DON MARIO 6.2I"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 6.8I" , value: "DON MARIO: SOJA | DON MARIO 6.8I"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 6200" , value: "DON MARIO: SOJA | DON MARIO 6200"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 6400" , value: "DON MARIO: SOJA | DON MARIO 6400"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 6500" , value: "DON MARIO: SOJA | DON MARIO 6500"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 6600" , value: "DON MARIO: SOJA | DON MARIO 6600"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 6800" , value: "DON MARIO: SOJA | DON MARIO 6800"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 7.0I" , value: "DON MARIO: SOJA | DON MARIO 7.0I"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 7.8 I" , value: "DON MARIO: SOJA | DON MARIO 7.8 I"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 8001" , value: "DON MARIO: SOJA | DON MARIO 8001"},
{obtentor:'DON MARIO',Cultivo: "SOJA" , variedad: "DON MARIO 8002" , value: "DON MARIO: SOJA | DON MARIO 8002"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO 3890" , value: "HORUS: SOJA | HO 3890"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO 3998" , value: "HORUS: SOJA | HO 3998"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO 4119 IPRO" , value: "HORUS: SOJA | HO 4119 IPRO"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO 4880" , value: "HORUS: SOJA | HO 4880"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO 4919 IPRO" , value: "HORUS: SOJA | HO 4919 IPRO"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO 5010" , value: "HORUS: SOJA | HO 5010"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO 5310 IPRO" , value: "HORUS: SOJA | HO 5310 IPRO"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO 5910" , value: "HORUS: SOJA | HO 5910"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO 6110 IPRO" , value: "HORUS: SOJA | HO 6110 IPRO"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO 6620 IPRO" , value: "HORUS: SOJA | HO 6620 IPRO"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO 6997 IPRO" , value: "HORUS: SOJA | HO 6997 IPRO"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO 74134 IPRO STS" , value: "HORUS: SOJA | HO 74134 IPRO STS"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO 7510 IPRO" , value: "HORUS: SOJA | HO 7510 IPRO"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO47147" , value: "HORUS: SOJA | HO47147"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO50135 STS" , value: "HORUS: SOJA | HO50135 STS"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO59136 IPRO" , value: "HORUS: SOJA | HO59136 IPRO"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HO68128 STS" , value: "HORUS: SOJA | HO68128 STS"},
{obtentor:'HORUS',Cultivo: "SOJA" , variedad: "HS 53140" , value: "HORUS: SOJA | HS 53140"},
{obtentor:'ILLINOIS',Cultivo: "SOJA" , variedad: "IS 3909" , value: "ILLINOIS: SOJA | IS 3909"},
{obtentor:'ILLINOIS',Cultivo: "SOJA" , variedad: "IS 46.2 RR STS" , value: "ILLINOIS: SOJA | IS 46.2 RR STS"},
{obtentor:'ILLINOIS',Cultivo: "SOJA" , variedad: "IS 46.5 RRSTS" , value: "ILLINOIS: SOJA | IS 46.5 RRSTS"},
{obtentor:'ILLINOIS',Cultivo: "SOJA" , variedad: "IS 4777" , value: "ILLINOIS: SOJA | IS 4777"},
{obtentor:'ILLINOIS',Cultivo: "SOJA" , variedad: "IS 52.0 RRSTS" , value: "ILLINOIS: SOJA | IS 52.0 RRSTS"},
{obtentor:'ILLINOIS',Cultivo: "SOJA" , variedad: "IS 62.1 IPRO STS" , value: "ILLINOIS: SOJA | IS 62.1 IPRO STS"},
{obtentor:'KLEIN',Cultivo: "SOJA" , variedad: "SK 3.5" , value: "KLEIN: SOJA | SK 3.5"},
{obtentor:'KLEIN',Cultivo: "SOJA" , variedad: "SK 3.8" , value: "KLEIN: SOJA | SK 3.8"},
{obtentor:'KLEIN',Cultivo: "SOJA" , variedad: "SK 4.7" , value: "KLEIN: SOJA | SK 4.7"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "3301" , value: "MACROSEED: SOJA | 3301"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "3701" , value: "MACROSEED: SOJA | 3701"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "41MS01" , value: "MACROSEED: SOJA | 41MS01"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "46MS01" , value: "MACROSEED: SOJA | 46MS01"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "47MS01" , value: "MACROSEED: SOJA | 47MS01"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "50MS01" , value: "MACROSEED: SOJA | 50MS01"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "53MS01 IPRO" , value: "MACROSEED: SOJA | 53MS01 IPRO"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "53MS02 STS" , value: "MACROSEED: SOJA | 53MS02 STS"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "59MS01 IPRO" , value: "MACROSEED: SOJA | 59MS01 IPRO"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "60MS01" , value: "MACROSEED: SOJA | 60MS01"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "62MS01 IPRO" , value: "MACROSEED: SOJA | 62MS01 IPRO"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "66MS01" , value: "MACROSEED: SOJA | 66MS01"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "78MS01 IPRO" , value: "MACROSEED: SOJA | 78MS01 IPRO"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "LDC 3.7" , value: "MACROSEED: SOJA | LDC 3.7"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "LDC 3.8" , value: "MACROSEED: SOJA | LDC 3.8"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "LDC 4.5" , value: "MACROSEED: SOJA | LDC 4.5"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "LDC 4.9" , value: "MACROSEED: SOJA | LDC 4.9"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "LDC 5.3" , value: "MACROSEED: SOJA | LDC 5.3"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "LDC 5.9" , value: "MACROSEED: SOJA | LDC 5.9"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "LDC 6.0" , value: "MACROSEED: SOJA | LDC 6.0"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "LDC 6.9" , value: "MACROSEED: SOJA | LDC 6.9"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "LDC 8.5" , value: "MACROSEED: SOJA | LDC 8.5"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "LDS 4.2" , value: "MACROSEED: SOJA | LDS 4.2"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "LDS 4.7" , value: "MACROSEED: SOJA | LDS 4.7"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "LDS 5.6" , value: "MACROSEED: SOJA | LDS 5.6"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "LDS 6.2" , value: "MACROSEED: SOJA | LDS 6.2"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "MS 4.0 IPRO" , value: "MACROSEED: SOJA | MS 4.0 IPRO"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "MS 4.4 IPRO" , value: "MACROSEED: SOJA | MS 4.4 IPRO"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "MS 4.9 IPRO" , value: "MACROSEED: SOJA | MS 4.9 IPRO"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "MS 6.3 IPRO" , value: "MACROSEED: SOJA | MS 6.3 IPRO"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "MS 6.9 IPRO" , value: "MACROSEED: SOJA | MS 6.9 IPRO"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "MS 6801 IPRO" , value: "MACROSEED: SOJA | MS 6801 IPRO"},
{obtentor:'MACROSEED',Cultivo: "SOJA" , variedad: "MS 7.4 IPRO" , value: "MACROSEED: SOJA | MS 7.4 IPRO"},
{obtentor:'NEOGEN',Cultivo: "SOJA" , variedad: "61S22 IPRO STS" , value: "NEOGEN: SOJA | 61S22 IPRO STS"},
{obtentor:'NEOGEN',Cultivo: "SOJA" , variedad: "NEO 45S22 RR STS" , value: "NEOGEN: SOJA | NEO 45S22 RR STS"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 3302 RG" , value: "NIDERA: SOJA | A 3302 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 3401 RG" , value: "NIDERA: SOJA | A 3401 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 3550 RG" , value: "NIDERA: SOJA | A 3550 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 3770RG" , value: "NIDERA: SOJA | A 3770RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 4201 RG" , value: "NIDERA: SOJA | A 4201 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 4303 RG" , value: "NIDERA: SOJA | A 4303 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 4404 RG" , value: "NIDERA: SOJA | A 4404 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 4423 RG" , value: "NIDERA: SOJA | A 4423 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 4505 RG" , value: "NIDERA: SOJA | A 4505 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 4725 RG" , value: "NIDERA: SOJA | A 4725 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 4910 RG" , value: "NIDERA: SOJA | A 4910 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 5409 RG" , value: "NIDERA: SOJA | A 5409 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 5417 RG" , value: "NIDERA: SOJA | A 5417 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 5428 RG" , value: "NIDERA: SOJA | A 5428 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 5503" , value: "NIDERA: SOJA | A 5503"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 5520 RG" , value: "NIDERA: SOJA | A 5520 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 5625 RG" , value: "NIDERA: SOJA | A 5625 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 5777 RG" , value: "NIDERA: SOJA | A 5777 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 5901 RG" , value: "NIDERA: SOJA | A 5901 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 6019 RG" , value: "NIDERA: SOJA | A 6019 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 6040 RG" , value: "NIDERA: SOJA | A 6040 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 6411 RG" , value: "NIDERA: SOJA | A 6411 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 7053 RG" , value: "NIDERA: SOJA | A 7053 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 7118 RG" , value: "NIDERA: SOJA | A 7118 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 7321 RG" , value: "NIDERA: SOJA | A 7321 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 7322 RG" , value: "NIDERA: SOJA | A 7322 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 7636 RG" , value: "NIDERA: SOJA | A 7636 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 8000 RG" , value: "NIDERA: SOJA | A 8000 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 8100 RG" , value: "NIDERA: SOJA | A 8100 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "A 9000 RG" , value: "NIDERA: SOJA | A 9000 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "AFA 5547 RG" , value: "NIDERA: SOJA | AFA 5547 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "AFA 5580RG" , value: "NIDERA: SOJA | AFA 5580RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "CAIS 4430 RG" , value: "NIDERA: SOJA | CAIS 4430 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "CCLP 6010 RG" , value: "NIDERA: SOJA | CCLP 6010 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "CH 4308 RG" , value: "NIDERA: SOJA | CH 4308 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "DL 4012 RG" , value: "NIDERA: SOJA | DL 4012 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "DL 4716RG" , value: "NIDERA: SOJA | DL 4716RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "EBC 4000RG" , value: "NIDERA: SOJA | EBC 4000RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "EBC 4900 RG" , value: "NIDERA: SOJA | EBC 4900 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "LAR 4920RG" , value: "NIDERA: SOJA | LAR 4920RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "MAN 6043 RG" , value: "NIDERA: SOJA | MAN 6043 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "MG 4969 RG" , value: "NIDERA: SOJA | MG 4969 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "MG 5631 RG" , value: "NIDERA: SOJA | MG 5631 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NA 3005 RG" , value: "NIDERA: SOJA | NA 3005 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 3289 RG" , value: "NIDERA: SOJA | NIDERA A 3289 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 3726 RG" , value: "NIDERA: SOJA | NIDERA A 3726 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 3731 RG" , value: "NIDERA: SOJA | NIDERA A 3731 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 3933 RG" , value: "NIDERA: SOJA | NIDERA A 3933 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 4209 RG" , value: "NIDERA: SOJA | NIDERA A 4209 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 4413RG" , value: "NIDERA: SOJA | NIDERA A 4413RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 4553 RG" , value: "NIDERA: SOJA | NIDERA A 4553 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 4613 RG" , value: "NIDERA: SOJA | NIDERA A 4613 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 4990 RG" , value: "NIDERA: SOJA | NIDERA A 4990 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 5009 RG" , value: "NIDERA: SOJA | NIDERA A 5009 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 5209RG" , value: "NIDERA: SOJA | NIDERA A 5209RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 5485 RG" , value: "NIDERA: SOJA | NIDERA A 5485 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 5509RG" , value: "NIDERA: SOJA | NIDERA A 5509RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 5543 RG" , value: "NIDERA: SOJA | NIDERA A 5543 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 5766 RG" , value: "NIDERA: SOJA | NIDERA A 5766 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 5909RG" , value: "NIDERA: SOJA | NIDERA A 5909RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 6126 RG" , value: "NIDERA: SOJA | NIDERA A 6126 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 6355 RG" , value: "NIDERA: SOJA | NIDERA A 6355 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 6509 RG" , value: "NIDERA: SOJA | NIDERA A 6509 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 7000 RG" , value: "NIDERA: SOJA | NIDERA A 7000 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 7708 RG" , value: "NIDERA: SOJA | NIDERA A 7708 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 8009 RG" , value: "NIDERA: SOJA | NIDERA A 8009 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 8010 RG" , value: "NIDERA: SOJA | NIDERA A 8010 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 8087 RG" , value: "NIDERA: SOJA | NIDERA A 8087 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 8164 RG" , value: "NIDERA: SOJA | NIDERA A 8164 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 8413 RG" , value: "NIDERA: SOJA | NIDERA A 8413 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA A 8499 RG" , value: "NIDERA: SOJA | NIDERA A 8499 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NIDERA X 3584 RG" , value: "NIDERA: SOJA | NIDERA X 3584 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 2018" , value: "NIDERA: SOJA | NS 2018"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 2632" , value: "NIDERA: SOJA | NS 2632"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 3215" , value: "NIDERA: SOJA | NS 3215"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 3220" , value: "NIDERA: SOJA | NS 3220"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 3313" , value: "NIDERA: SOJA | NS 3313"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 3809IPRO" , value: "NIDERA: SOJA | NS 3809IPRO"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 3821 STS" , value: "NIDERA: SOJA | NS 3821 STS"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 3909" , value: "NIDERA: SOJA | NS 3909"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 4009" , value: "NIDERA: SOJA | NS 4009"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 4309" , value: "NIDERA: SOJA | NS 4309"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 4313" , value: "NIDERA: SOJA | NS 4313"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 4319 IPRO" , value: "NIDERA: SOJA | NS 4319 IPRO"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 4611" , value: "NIDERA: SOJA | NS 4611"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 4619 IPRO" , value: "NIDERA: SOJA | NS 4619 IPRO"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 4621 IPRO STS" , value: "NIDERA: SOJA | NS 4621 IPRO STS"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 4642 STS" , value: "NIDERA: SOJA | NS 4642 STS"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 4903" , value: "NIDERA: SOJA | NS 4903"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 4955" , value: "NIDERA: SOJA | NS 4955"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 4997" , value: "NIDERA: SOJA | NS 4997"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 5019 IPRO" , value: "NIDERA: SOJA | NS 5019 IPRO"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 5028 STS" , value: "NIDERA: SOJA | NS 5028 STS"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 5030 IPRO STS" , value: "NIDERA: SOJA | NS 5030 IPRO STS"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 5230" , value: "NIDERA: SOJA | NS 5230"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 5258" , value: "NIDERA: SOJA | NS 5258"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 5419IPRO" , value: "NIDERA: SOJA | NS 5419IPRO"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 5421 STS" , value: "NIDERA: SOJA | NS 5421 STS"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 6002" , value: "NIDERA: SOJA | NS 6002"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 6120 IPRO" , value: "NIDERA: SOJA | NS 6120 IPRO"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 6212 IPRO" , value: "NIDERA: SOJA | NS 6212 IPRO"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 6248" , value: "NIDERA: SOJA | NS 6248"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 6267" , value: "NIDERA: SOJA | NS 6267"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 6419 IPRO" , value: "NIDERA: SOJA | NS 6419 IPRO"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 6448" , value: "NIDERA: SOJA | NS 6448"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 6483" , value: "NIDERA: SOJA | NS 6483"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 6517" , value: "NIDERA: SOJA | NS 6517"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 6538 IPRO" , value: "NIDERA: SOJA | NS 6538 IPRO"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 6721 IPRO STS" , value: "NIDERA: SOJA | NS 6721 IPRO STS"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 6859IPRO" , value: "NIDERA: SOJA | NS 6859IPRO"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 6909 IPRO" , value: "NIDERA: SOJA | NS 6909 IPRO"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 7209 I PRO" , value: "NIDERA: SOJA | NS 7209 I PRO"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 7211" , value: "NIDERA: SOJA | NS 7211"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 7273" , value: "NIDERA: SOJA | NS 7273"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 7709 IPRO" , value: "NIDERA: SOJA | NS 7709 IPRO"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 7711 I PRO" , value: "NIDERA: SOJA | NS 7711 I PRO"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 7809" , value: "NIDERA: SOJA | NS 7809"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 7922 IPRO" , value: "NIDERA: SOJA | NS 7922 IPRO"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 8004" , value: "NIDERA: SOJA | NS 8004"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 8018 IPRO STS" , value: "NIDERA: SOJA | NS 8018 IPRO STS"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 8043" , value: "NIDERA: SOJA | NS 8043"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 8262" , value: "NIDERA: SOJA | NS 8262"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 8282" , value: "NIDERA: SOJA | NS 8282"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS 8288" , value: "NIDERA: SOJA | NS 8288"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "NS7300 I PRO" , value: "NIDERA: SOJA | NS7300 I PRO"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "ROJAS 3902 RG" , value: "NIDERA: SOJA | ROJAS 3902 RG"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "Tolvas 3909" , value: "NIDERA: SOJA | Tolvas 3909"},
{obtentor:'NIDERA',Cultivo: "SOJA" , variedad: "TOMAS 3604 RG" , value: "NIDERA: SOJA | TOMAS 3604 RG"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "49X20 IPRO STS" , value: "NK SEMILLAS: SOJA | 49X20 IPRO STS"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "4X5" , value: "NK SEMILLAS: SOJA | 4X5"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "7X1 IPRO" , value: "NK SEMILLAS: SOJA | 7X1 IPRO"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "80X20 IPRO STS" , value: "NK SEMILLAS: SOJA | 80X20 IPRO STS"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK 32-00" , value: "NK SEMILLAS: SOJA | NK 32-00"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK 33X22 STS" , value: "NK SEMILLAS: SOJA | NK 33X22 STS"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK 34-00" , value: "NK SEMILLAS: SOJA | NK 34-00"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK 35-00" , value: "NK SEMILLAS: SOJA | NK 35-00"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK 37-00" , value: "NK SEMILLAS: SOJA | NK 37-00"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK 38-00" , value: "NK SEMILLAS: SOJA | NK 38-00"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK 39-00" , value: "NK SEMILLAS: SOJA | NK 39-00"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK 39X22 STS" , value: "NK SEMILLAS: SOJA | NK 39X22 STS"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK 43-00" , value: "NK SEMILLAS: SOJA | NK 43-00"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK 47-00" , value: "NK SEMILLAS: SOJA | NK 47-00"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK 48-00" , value: "NK SEMILLAS: SOJA | NK 48-00"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK 52X21 STS" , value: "NK SEMILLAS: SOJA | NK 52X21 STS"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK 60X21 IPRO STS" , value: "NK SEMILLAS: SOJA | NK 60X21 IPRO STS"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK COKER 6.6" , value: "NK SEMILLAS: SOJA | NK COKER 6.6"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK COKER 6.8 R" , value: "NK SEMILLAS: SOJA | NK COKER 6.8 R"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK COKER 7.5 R" , value: "NK SEMILLAS: SOJA | NK COKER 7.5 R"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK COKER 80" , value: "NK SEMILLAS: SOJA | NK COKER 80"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK MIREYA 4.2" , value: "NK SEMILLAS: SOJA | NK MIREYA 4.2"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "NK PICASA 4.0" , value: "NK SEMILLAS: SOJA | NK PICASA 4.0"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "S 4x6 IPRO" , value: "NK SEMILLAS: SOJA | S 4x6 IPRO"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SA 4900" , value: "NK SEMILLAS: SOJA | SA 4900"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 3900" , value: "NK SEMILLAS: SOJA | SP 3900"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 3X1" , value: "NK SEMILLAS: SOJA | SP 3X1"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 4500" , value: "NK SEMILLAS: SOJA | SP 4500"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 4X0" , value: "NK SEMILLAS: SOJA | SP 4X0"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 4X2" , value: "NK SEMILLAS: SOJA | SP 4X2"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 4X3 IPRO" , value: "NK SEMILLAS: SOJA | SP 4X3 IPRO"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 4X4" , value: "NK SEMILLAS: SOJA | SP 4X4"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 4X99" , value: "NK SEMILLAS: SOJA | SP 4X99"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 5X2" , value: "NK SEMILLAS: SOJA | SP 5X2"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 5X5" , value: "NK SEMILLAS: SOJA | SP 5X5"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 5X9" , value: "NK SEMILLAS: SOJA | SP 5X9"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 6X1" , value: "NK SEMILLAS: SOJA | SP 6X1"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 6X2" , value: "NK SEMILLAS: SOJA | SP 6X2"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 6X6 IPRO" , value: "NK SEMILLAS: SOJA | SP 6X6 IPRO"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 7X0" , value: "NK SEMILLAS: SOJA | SP 7X0"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 7x8 IPRO" , value: "NK SEMILLAS: SOJA | SP 7x8 IPRO"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 8X0" , value: "NK SEMILLAS: SOJA | SP 8X0"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SP 8X8" , value: "NK SEMILLAS: SOJA | SP 8X8"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SPS 3800" , value: "NK SEMILLAS: SOJA | SPS 3800"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SY 3X5" , value: "NK SEMILLAS: SOJA | SY 3X5"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SY 3x7" , value: "NK SEMILLAS: SOJA | SY 3x7"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SY 3X9" , value: "NK SEMILLAS: SOJA | SY 3X9"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SY 4X1" , value: "NK SEMILLAS: SOJA | SY 4X1"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SY 4X9" , value: "NK SEMILLAS: SOJA | SY 4X9"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SY 5X1" , value: "NK SEMILLAS: SOJA | SY 5X1"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SY 5X2 IPRO" , value: "NK SEMILLAS: SOJA | SY 5X2 IPRO"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SY 5X8 IPRO" , value: "NK SEMILLAS: SOJA | SY 5X8 IPRO"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SY 6X8 IPRO" , value: "NK SEMILLAS: SOJA | SY 6X8 IPRO"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SY COKER 7X3" , value: "NK SEMILLAS: SOJA | SY COKER 7X3"},
{obtentor:'NK SEMILLAS',Cultivo: "SOJA" , variedad: "SYN 1561 IPRO" , value: "NK SEMILLAS: SOJA | SYN 1561 IPRO"},
{obtentor:'NUTRIEN',Cultivo: "SOJA" , variedad: "AS 3601" , value: "NUTRIEN: SOJA | AS 3601"},
{obtentor:'NUTRIEN',Cultivo: "SOJA" , variedad: "AS 3911" , value: "NUTRIEN: SOJA | AS 3911"},
{obtentor:'NUTRIEN',Cultivo: "SOJA" , variedad: "AS 4201" , value: "NUTRIEN: SOJA | AS 4201"},
{obtentor:'NUTRIEN',Cultivo: "SOJA" , variedad: "AS 4402" , value: "NUTRIEN: SOJA | AS 4402"},
{obtentor:'NUTRIEN',Cultivo: "SOJA" , variedad: "AS 4731" , value: "NUTRIEN: SOJA | AS 4731"},
{obtentor:'NUTRIEN',Cultivo: "SOJA" , variedad: "AS 4801" , value: "NUTRIEN: SOJA | AS 4801"},
{obtentor:'NUTRIEN',Cultivo: "SOJA" , variedad: "AS 4931" , value: "NUTRIEN: SOJA | AS 4931"},
{obtentor:'NUTRIEN',Cultivo: "SOJA" , variedad: "AS 5308 I" , value: "NUTRIEN: SOJA | AS 5308 I"},
{obtentor:'NUTRIEN',Cultivo: "SOJA" , variedad: "AS 5961" , value: "NUTRIEN: SOJA | AS 5961"},
{obtentor:'NUTRIEN',Cultivo: "SOJA" , variedad: "DYN 3525" , value: "NUTRIEN: SOJA | DYN 3525"},
{obtentor:'NUTRIEN',Cultivo: "SOJA" , variedad: "DYN 5325" , value: "NUTRIEN: SOJA | DYN 5325"},
{obtentor:'PIONEER',Cultivo: "SOJA" , variedad: "93M70" , value: "PIONEER: SOJA | 93M70"},
{obtentor:'PIONEER',Cultivo: "SOJA" , variedad: "93M92" , value: "PIONEER: SOJA | 93M92"},
{obtentor:'PIONEER',Cultivo: "SOJA" , variedad: "93M96" , value: "PIONEER: SOJA | 93M96"},
{obtentor:'PIONEER',Cultivo: "SOJA" , variedad: "94M30" , value: "PIONEER: SOJA | 94M30"},
{obtentor:'PIONEER',Cultivo: "SOJA" , variedad: "94M80" , value: "PIONEER: SOJA | 94M80"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "5715 IPRO" , value: "SANTA ROSA: SOJA | 5715 IPRO"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "6615 IPRO" , value: "SANTA ROSA: SOJA | 6615 IPRO"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "GA 645" , value: "SANTA ROSA: SOJA | GA 645"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 334" , value: "SANTA ROSA: SOJA | RA 334"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 338" , value: "SANTA ROSA: SOJA | RA 338"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 349" , value: "SANTA ROSA: SOJA | RA 349"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 437" , value: "SANTA ROSA: SOJA | RA 437"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 444" , value: "SANTA ROSA: SOJA | RA 444"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 4458" , value: "SANTA ROSA: SOJA | RA 4458"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 449" , value: "SANTA ROSA: SOJA | RA 449"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 532" , value: "SANTA ROSA: SOJA | RA 532"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 536" , value: "SANTA ROSA: SOJA | RA 536"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 538" , value: "SANTA ROSA: SOJA | RA 538"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 541" , value: "SANTA ROSA: SOJA | RA 541"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 545" , value: "SANTA ROSA: SOJA | RA 545"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 549" , value: "SANTA ROSA: SOJA | RA 549"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 550" , value: "SANTA ROSA: SOJA | RA 550"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 556" , value: "SANTA ROSA: SOJA | RA 556"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 569" , value: "SANTA ROSA: SOJA | RA 569"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 644" , value: "SANTA ROSA: SOJA | RA 644"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 655" , value: "SANTA ROSA: SOJA | RA 655"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 659" , value: "SANTA ROSA: SOJA | RA 659"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 732" , value: "SANTA ROSA: SOJA | RA 732"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 733" , value: "SANTA ROSA: SOJA | RA 733"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 744" , value: "SANTA ROSA: SOJA | RA 744"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 750" , value: "SANTA ROSA: SOJA | RA 750"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA 844" , value: "SANTA ROSA: SOJA | RA 844"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA332" , value: "SANTA ROSA: SOJA | RA332"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA3916" , value: "SANTA ROSA: SOJA | RA3916"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA4318 TS" , value: "SANTA ROSA: SOJA | RA4318 TS"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA5217" , value: "SANTA ROSA: SOJA | RA5217"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA5816" , value: "SANTA ROSA: SOJA | RA5816"},
{obtentor:'SANTA ROSA',Cultivo: "SOJA" , variedad: "RA652" , value: "SANTA ROSA: SOJA | RA652"},
{obtentor:'SEEDAR',Cultivo: "SOJA" , variedad: "ROSANA INTA 3.9 STS" , value: "SEEDAR: SOJA | ROSANA INTA 3.9 STS"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "3970" , value: "SURSEM: SOJA | 3970"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "4301" , value: "SURSEM: SOJA | 4301"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "4370" , value: "SURSEM: SOJA | 4370"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "4901" , value: "SURSEM: SOJA | 4901"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "5835IPRO" , value: "SURSEM: SOJA | 5835IPRO"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "6124" , value: "SURSEM: SOJA | 6124"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "AGUSTINA 49" , value: "SURSEM: SOJA | AGUSTINA 49"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "ANDREA 60" , value: "SURSEM: SOJA | ANDREA 60"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "ANDREA 63" , value: "SURSEM: SOJA | ANDREA 63"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "ANTA 80" , value: "SURSEM: SOJA | ANTA 80"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "ANTA 81" , value: "SURSEM: SOJA | ANTA 81"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "ANTA 82" , value: "SURSEM: SOJA | ANTA 82"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "ANTA 83" , value: "SURSEM: SOJA | ANTA 83"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "AW 3370" , value: "SURSEM: SOJA | AW 3370"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "AYELEN 22" , value: "SURSEM: SOJA | AYELEN 22"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "AZUL 35" , value: "SURSEM: SOJA | AZUL 35"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "CRISTINA 64" , value: "SURSEM: SOJA | CRISTINA 64"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "LEO7800" , value: "SURSEM: SOJA | LEO7800"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "MARIA 50" , value: "SURSEM: SOJA | MARIA 50"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "MERCEDES 76" , value: "SURSEM: SOJA | MERCEDES 76"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "N49R" , value: "SURSEM: SOJA | N49R"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "NA66R" , value: "SURSEM: SOJA | NA66R"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "NM55R" , value: "SURSEM: SOJA | NM55R"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "NM70R" , value: "SURSEM: SOJA | NM70R"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RAFAELA 58" , value: "SURSEM: SOJA | RAFAELA 58"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RM 3300" , value: "SURSEM: SOJA | RM 3300"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RM 3801" , value: "SURSEM: SOJA | RM 3801"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RM 4839" , value: "SURSEM: SOJA | RM 4839"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RM 5500" , value: "SURSEM: SOJA | RM 5500"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RM 5601" , value: "SURSEM: SOJA | RM 5601"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RM 5700" , value: "SURSEM: SOJA | RM 5700"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RM 6001" , value: "SURSEM: SOJA | RM 6001"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RM 6900" , value: "SURSEM: SOJA | RM 6900"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RM 7200" , value: "SURSEM: SOJA | RM 7200"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RM 7800" , value: "SURSEM: SOJA | RM 7800"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RM 8201" , value: "SURSEM: SOJA | RM 8201"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RMO 4637" , value: "SURSEM: SOJA | RMO 4637"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RMO 58" , value: "SURSEM: SOJA | RMO 58"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RMO 75" , value: "SURSEM: SOJA | RMO 75"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RMO 77" , value: "SURSEM: SOJA | RMO 77"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RMO 805" , value: "SURSEM: SOJA | RMO 805"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RMO37" , value: "SURSEM: SOJA | RMO37"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RMO39" , value: "SURSEM: SOJA | RMO39"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RMO48" , value: "SURSEM: SOJA | RMO48"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RMO57" , value: "SURSEM: SOJA | RMO57"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "RMO67" , value: "SURSEM: SOJA | RMO67"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SR 5406" , value: "SURSEM: SOJA | SR 5406"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM 2801" , value: "SURSEM: SOJA | SRM 2801"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM 3410" , value: "SURSEM: SOJA | SRM 3410"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM 3988" , value: "SURSEM: SOJA | SRM 3988"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM 4222" , value: "SURSEM: SOJA | SRM 4222"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM 4500" , value: "SURSEM: SOJA | SRM 4500"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM 4602" , value: "SURSEM: SOJA | SRM 4602"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM 4754" , value: "SURSEM: SOJA | SRM 4754"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM 5001" , value: "SURSEM: SOJA | SRM 5001"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM 5037" , value: "SURSEM: SOJA | SRM 5037"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM 5200" , value: "SURSEM: SOJA | SRM 5200"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM 5301" , value: "SURSEM: SOJA | SRM 5301"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM 5951" , value: "SURSEM: SOJA | SRM 5951"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM 6256" , value: "SURSEM: SOJA | SRM 6256"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM 6403" , value: "SURSEM: SOJA | SRM 6403"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM5944" , value: "SURSEM: SOJA | SRM5944"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM6595" , value: "SURSEM: SOJA | SRM6595"},
{obtentor:'SURSEM',Cultivo: "SOJA" , variedad: "SRM7400" , value: "SURSEM: SOJA | SRM7400"},
{obtentor:'TOBIN',Cultivo: "SOJA" , variedad: "LEO 6401" , value: "TOBIN: SOJA | LEO 6401"},
{obtentor:'TOBIN',Cultivo: "SOJA" , variedad: "LEO 7800" , value: "TOBIN: SOJA | LEO 7800"},
{obtentor:'VETAGRO',Cultivo: "SOJA" , variedad: "MUNASQA" , value: "VETAGRO: SOJA | MUNASQA"},
{obtentor:'VETAGRO',Cultivo: "SOJA" , variedad: "TUKUY" , value: "VETAGRO: SOJA | TUKUY"},
{obtentor:'VETAGRO',Cultivo: "SOJA" , variedad: "YANASU" , value: "VETAGRO: SOJA | YANASU"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "365" , value: "A.C.A.: TRIGO | 365"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "603" , value: "A.C.A.: TRIGO | 603"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "915" , value: "A.C.A.: TRIGO | 915"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "916" , value: "A.C.A.: TRIGO | 916"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "920" , value: "A.C.A.: TRIGO | 920"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "ACA 303 PLUS" , value: "A.C.A.: TRIGO | ACA 303 PLUS"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "ACA 308" , value: "A.C.A.: TRIGO | ACA 308"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "ACA 360" , value: "A.C.A.: TRIGO | ACA 360"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "ACA 362" , value: "A.C.A.: TRIGO | ACA 362"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "ACA 363" , value: "A.C.A.: TRIGO | ACA 363"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "ACA 364" , value: "A.C.A.: TRIGO | ACA 364"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "ACA 502" , value: "A.C.A.: TRIGO | ACA 502"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "ACA 602" , value: "A.C.A.: TRIGO | ACA 602"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "ACA 604" , value: "A.C.A.: TRIGO | ACA 604"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "ACA 605" , value: "A.C.A.: TRIGO | ACA 605"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "ACA 908" , value: "A.C.A.: TRIGO | ACA 908"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "ACA 909" , value: "A.C.A.: TRIGO | ACA 909"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "ACA 917" , value: "A.C.A.: TRIGO | ACA 917"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "CEDRO" , value: "A.C.A.: TRIGO | CEDRO"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "CIPRES" , value: "A.C.A.: TRIGO | CIPRES"},
{obtentor:'A.C.A.',Cultivo: "TRIGO" , variedad: "FRESNO" , value: "A.C.A.: TRIGO | FRESNO"},
{obtentor:'AGRISEED',Cultivo: "TRIGO" , variedad: "FLORIPAN 100" , value: "AGRISEED: TRIGO | FLORIPAN 100"},
{obtentor:'AGRISEED',Cultivo: "TRIGO" , variedad: "FLORIPAN 200" , value: "AGRISEED: TRIGO | FLORIPAN 200"},
{obtentor:'AGRISEED',Cultivo: "TRIGO" , variedad: "FLORIPAN 300" , value: "AGRISEED: TRIGO | FLORIPAN 300"},
{obtentor:'AGRISEED',Cultivo: "TRIGO" , variedad: "Floripan 301" , value: "AGRISEED: TRIGO | Floripan 301"},
{obtentor:'BARROW',Cultivo: "TRIGO" , variedad: "BONAERENSE INTA QUILLÉN" , value: "BARROW: TRIGO | BONAERENSE INTA QUILLÉN"},
{obtentor:'BARROW',Cultivo: "TRIGO" , variedad: "BONAERENSE MDA INTA CHARITO" , value: "BARROW: TRIGO | BONAERENSE MDA INTA CHARITO"},
{obtentor:'BARROW',Cultivo: "TRIGO" , variedad: "BONAERENSE MDA INTA GALPON" , value: "BARROW: TRIGO | BONAERENSE MDA INTA GALPON"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BASILIO" , value: "BIOCERES: TRIGO | BASILIO"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOCERES 1008" , value: "BIOCERES: TRIGO | BIOCERES 1008"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 1001" , value: "BIOCERES: TRIGO | BIOINTA 1001"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 1002" , value: "BIOCERES: TRIGO | BIOINTA 1002"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 1004" , value: "BIOCERES: TRIGO | BIOINTA 1004"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 1005" , value: "BIOCERES: TRIGO | BIOINTA 1005"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 1006" , value: "BIOCERES: TRIGO | BIOINTA 1006"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 1007" , value: "BIOCERES: TRIGO | BIOINTA 1007"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 2002" , value: "BIOCERES: TRIGO | BIOINTA 2002"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 2004" , value: "BIOCERES: TRIGO | BIOINTA 2004"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 2005" , value: "BIOCERES: TRIGO | BIOINTA 2005"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 2006" , value: "BIOCERES: TRIGO | BIOINTA 2006"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 3000" , value: "BIOCERES: TRIGO | BIOINTA 3000"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 3003" , value: "BIOCERES: TRIGO | BIOINTA 3003"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 3004" , value: "BIOCERES: TRIGO | BIOINTA 3004"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 3005" , value: "BIOCERES: TRIGO | BIOINTA 3005"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 3006" , value: "BIOCERES: TRIGO | BIOINTA 3006"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 3007 BB" , value: "BIOCERES: TRIGO | BIOINTA 3007 BB"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "BIOINTA 3008" , value: "BIOCERES: TRIGO | BIOINTA 3008"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "GINGKO" , value: "BIOCERES: TRIGO | GINGKO"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "GUAYABO" , value: "BIOCERES: TRIGO | GUAYABO"},
{obtentor:'BIOCERES',Cultivo: "TRIGO" , variedad: "TIMBO" , value: "BIOCERES: TRIGO | TIMBO"},
{obtentor:'BIOSEMINIS',Cultivo: "TRIGO" , variedad: "ÁLAMO" , value: "BIOSEMINIS: TRIGO | ÁLAMO"},
{obtentor:'BIOSEMINIS',Cultivo: "TRIGO" , variedad: "JACARANDA" , value: "BIOSEMINIS: TRIGO | JACARANDA"},
{obtentor:'BIOSEMINIS',Cultivo: "TRIGO" , variedad: "SARANDI" , value: "BIOSEMINIS: TRIGO | SARANDI"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "55 CL 2" , value: "BUCK: TRIGO | 55 CL 2"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "AGP 127" , value: "BUCK: TRIGO | AGP 127"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "AGP FAST" , value: "BUCK: TRIGO | AGP FAST"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK 75 ANIVERSARIO" , value: "BUCK: TRIGO | BUCK 75 ANIVERSARIO"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK AIMARÁ" , value: "BUCK: TRIGO | BUCK AIMARÁ"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK AMANCAY" , value: "BUCK: TRIGO | BUCK AMANCAY"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK BELLACO" , value: "BUCK: TRIGO | BUCK BELLACO"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK BRAVIO CL2" , value: "BUCK: TRIGO | BUCK BRAVIO CL2"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK CAMBÁ" , value: "BUCK: TRIGO | BUCK CAMBÁ"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK CLARAZ" , value: "BUCK: TRIGO | BUCK CLARAZ"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK COLIHUE" , value: "BUCK: TRIGO | BUCK COLIHUE"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK CUARZO" , value: "BUCK: TRIGO | BUCK CUARZO"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK CUMELEN" , value: "BUCK: TRIGO | BUCK CUMELEN"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK DESTELLO" , value: "BUCK: TRIGO | BUCK DESTELLO"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK FULGOR" , value: "BUCK: TRIGO | BUCK FULGOR"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK METEORO" , value: "BUCK: TRIGO | BUCK METEORO"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK MUTISIA" , value: "BUCK: TRIGO | BUCK MUTISIA"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK PACIFICO" , value: "BUCK: TRIGO | BUCK PACIFICO"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK PEREGRINO" , value: "BUCK: TRIGO | BUCK PEREGRINO"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK PERLA" , value: "BUCK: TRIGO | BUCK PERLA"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK PLENO" , value: "BUCK: TRIGO | BUCK PLENO"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK PRETAL" , value: "BUCK: TRIGO | BUCK PRETAL"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK RESPLANDOR" , value: "BUCK: TRIGO | BUCK RESPLANDOR"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK SAETA" , value: "BUCK: TRIGO | BUCK SAETA"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK TAITA" , value: "BUCK: TRIGO | BUCK TAITA"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK TILCARA" , value: "BUCK: TRIGO | BUCK TILCARA"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCK ZAFIRO" , value: "BUCK: TRIGO | BUCK ZAFIRO"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "BUCKRUBI" , value: "BUCK: TRIGO | BUCKRUBI"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "OBELIX" , value: "BUCK: TRIGO | OBELIX"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "ODISSEO" , value: "BUCK: TRIGO | ODISSEO"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "SY 015" , value: "BUCK: TRIGO | SY 015"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "SY 041" , value: "BUCK: TRIGO | SY 041"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "SY 100" , value: "BUCK: TRIGO | SY 100"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "SY 109" , value: "BUCK: TRIGO | SY 109"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "SY 110" , value: "BUCK: TRIGO | SY 110"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "SY 120" , value: "BUCK: TRIGO | SY 120"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "SY 200" , value: "BUCK: TRIGO | SY 200"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "SY 211" , value: "BUCK: TRIGO | SY 211"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "SY 300" , value: "BUCK: TRIGO | SY 300"},
{obtentor:'BUCK',Cultivo: "TRIGO" , variedad: "SY330" , value: "BUCK: TRIGO | SY330"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "ALERCE" , value: "DON MARIO: TRIGO | ALERCE"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "ALGARROBO" , value: "DON MARIO: TRIGO | ALGARROBO"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "AREX" , value: "DON MARIO: TRIGO | AREX"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "AROMO" , value: "DON MARIO: TRIGO | AROMO"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "ATLAX" , value: "DON MARIO: TRIGO | ATLAX"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "CAMBIUM" , value: "DON MARIO: TRIGO | CAMBIUM"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "CATALPA" , value: "DON MARIO: TRIGO | CATALPA"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "CEIBO" , value: "DON MARIO: TRIGO | CEIBO"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "CRONOX" , value: "DON MARIO: TRIGO | CRONOX"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "FUSTE" , value: "DON MARIO: TRIGO | FUSTE"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "LENGA" , value: "DON MARIO: TRIGO | LENGA"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "LENOX" , value: "DON MARIO: TRIGO | LENOX"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "LYON" , value: "DON MARIO: TRIGO | LYON"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "ÑANDUBAY" , value: "DON MARIO: TRIGO | ÑANDUBAY"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "ONIX" , value: "DON MARIO: TRIGO | ONIX"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "PEHUEN" , value: "DON MARIO: TRIGO | PEHUEN"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "SAUCE" , value: "DON MARIO: TRIGO | SAUCE"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "TBIO AUDAZ" , value: "DON MARIO: TRIGO | TBIO AUDAZ"},
{obtentor:'DON MARIO',Cultivo: "TRIGO" , variedad: "THEMIX L" , value: "DON MARIO: TRIGO | THEMIX L"},
{obtentor:'HORUS',Cultivo: "TRIGO" , variedad: "HO ATUEL" , value: "HORUS: TRIGO | HO ATUEL"},
{obtentor:'HORUS',Cultivo: "TRIGO" , variedad: "HO CARCARAÑA" , value: "HORUS: TRIGO | HO CARCARAÑA"},
{obtentor:'ILLINOIS',Cultivo: "TRIGO" , variedad: "IS HORNERO" , value: "ILLINOIS: TRIGO | IS HORNERO"},
{obtentor:'ILLINOIS',Cultivo: "TRIGO" , variedad: "IS TERO" , value: "ILLINOIS: TRIGO | IS TERO"},
{obtentor:'ILLINOIS',Cultivo: "TRIGO" , variedad: "IS TORDO" , value: "ILLINOIS: TRIGO | IS TORDO"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN CAPRICORNIO" , value: "KLEIN: TRIGO | KLEIN CAPRICORNIO"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN CASTOR" , value: "KLEIN: TRIGO | KLEIN CASTOR"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN CIEN AÑOS" , value: "KLEIN: TRIGO | KLEIN CIEN AÑOS"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN FAVORITO II" , value: "KLEIN: TRIGO | KLEIN FAVORITO II"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN FLAMENCO" , value: "KLEIN: TRIGO | KLEIN FLAMENCO"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN GAVILAN" , value: "KLEIN: TRIGO | KLEIN GAVILAN"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN GEMINIS" , value: "KLEIN: TRIGO | KLEIN GEMINIS"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN GLADIADOR" , value: "KLEIN: TRIGO | KLEIN GLADIADOR"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN GUERRERO" , value: "KLEIN: TRIGO | KLEIN GUERRERO"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN HURACAN" , value: "KLEIN: TRIGO | KLEIN HURACAN"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN LANZA" , value: "KLEIN: TRIGO | KLEIN LANZA"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN LEON" , value: "KLEIN: TRIGO | KLEIN LEON"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN LIEBRE" , value: "KLEIN: TRIGO | KLEIN LIEBRE"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN MERCURIO" , value: "KLEIN: TRIGO | KLEIN MERCURIO"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN MINERVA" , value: "KLEIN: TRIGO | KLEIN MINERVA"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN NUTRIA" , value: "KLEIN: TRIGO | KLEIN NUTRIA"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN POTRO" , value: "KLEIN: TRIGO | KLEIN POTRO"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN PROTEO" , value: "KLEIN: TRIGO | KLEIN PROTEO"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN RAYO" , value: "KLEIN: TRIGO | KLEIN RAYO"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN ROBLE" , value: "KLEIN: TRIGO | KLEIN ROBLE"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN SELENIO CL" , value: "KLEIN: TRIGO | KLEIN SELENIO CL"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN SERPIENTE" , value: "KLEIN: TRIGO | KLEIN SERPIENTE"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN TAURO" , value: "KLEIN: TRIGO | KLEIN TAURO"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN TITANIO CL" , value: "KLEIN: TRIGO | KLEIN TITANIO CL"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN VALOR" , value: "KLEIN: TRIGO | KLEIN VALOR"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN YARARA" , value: "KLEIN: TRIGO | KLEIN YARARA"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEIN ZORRO" , value: "KLEIN: TRIGO | KLEIN ZORRO"},
{obtentor:'KLEIN',Cultivo: "TRIGO" , variedad: "KLEINPROMETEO" , value: "KLEIN: TRIGO | KLEINPROMETEO"},
{obtentor:'MACROSEED',Cultivo: "TRIGO" , variedad: "MS INTA 116" , value: "MACROSEED: TRIGO | MS INTA 116"},
{obtentor:'MACROSEED',Cultivo: "TRIGO" , variedad: "MS INTA 119" , value: "MACROSEED: TRIGO | MS INTA 119"},
{obtentor:'MACROSEED',Cultivo: "TRIGO" , variedad: "MS INTA 217" , value: "MACROSEED: TRIGO | MS INTA 217"},
{obtentor:'MACROSEED',Cultivo: "TRIGO" , variedad: "MS INTA 316" , value: "MACROSEED: TRIGO | MS INTA 316"},
{obtentor:'MACROSEED',Cultivo: "TRIGO" , variedad: "MS INTA 415" , value: "MACROSEED: TRIGO | MS INTA 415"},
{obtentor:'MACROSEED',Cultivo: "TRIGO" , variedad: "MS INTA 416" , value: "MACROSEED: TRIGO | MS INTA 416"},
{obtentor:'MACROSEED',Cultivo: "TRIGO" , variedad: "MS INTA 615" , value: "MACROSEED: TRIGO | MS INTA 615"},
{obtentor:'MACROSEED',Cultivo: "TRIGO" , variedad: "MS INTA 617" , value: "MACROSEED: TRIGO | MS INTA 617"},
{obtentor:'MACROSEED',Cultivo: "TRIGO" , variedad: "MS INTA 815" , value: "MACROSEED: TRIGO | MS INTA 815"},
{obtentor:'MACROSEED',Cultivo: "TRIGO" , variedad: "MS INTA BONAERENSE 215" , value: "MACROSEED: TRIGO | MS INTA BONAERENSE 215"},
{obtentor:'MACROSEED',Cultivo: "TRIGO" , variedad: "MS INTA BONAERENSE 514" , value: "MACROSEED: TRIGO | MS INTA BONAERENSE 514"},
{obtentor:'MACROSEED',Cultivo: "TRIGO" , variedad: "MS INTA BONAERENSE 516" , value: "MACROSEED: TRIGO | MS INTA BONAERENSE 516"},
{obtentor:'MACROSEED',Cultivo: "TRIGO" , variedad: "MS INTA BONAERENSE 816" , value: "MACROSEED: TRIGO | MS INTA BONAERENSE 816"},
{obtentor:'MACROSEED',Cultivo: "TRIGO" , variedad: "MS INTA BONAERENSE 817" , value: "MACROSEED: TRIGO | MS INTA BONAERENSE 817"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "ACIENDA" , value: "NIDERA: TRIGO | ACIENDA"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 10" , value: "NIDERA: TRIGO | BAGUETTE 10"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 17" , value: "NIDERA: TRIGO | BAGUETTE 17"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 18" , value: "NIDERA: TRIGO | BAGUETTE 18"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 19" , value: "NIDERA: TRIGO | BAGUETTE 19"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 20" , value: "NIDERA: TRIGO | BAGUETTE 20"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 30" , value: "NIDERA: TRIGO | BAGUETTE 30"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 31" , value: "NIDERA: TRIGO | BAGUETTE 31"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 450" , value: "NIDERA: TRIGO | BAGUETTE 450"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 501" , value: "NIDERA: TRIGO | BAGUETTE 501"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 550" , value: "NIDERA: TRIGO | BAGUETTE 550"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 560 CL" , value: "NIDERA: TRIGO | BAGUETTE 560 CL"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 601" , value: "NIDERA: TRIGO | BAGUETTE 601"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 620" , value: "NIDERA: TRIGO | BAGUETTE 620"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 680" , value: "NIDERA: TRIGO | BAGUETTE 680"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 701 PREMIUM" , value: "NIDERA: TRIGO | BAGUETTE 701 PREMIUM"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 750" , value: "NIDERA: TRIGO | BAGUETTE 750"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 801 PREMIUM" , value: "NIDERA: TRIGO | BAGUETTE 801 PREMIUM"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 802" , value: "NIDERA: TRIGO | BAGUETTE 802"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 820" , value: "NIDERA: TRIGO | BAGUETTE 820"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE 9" , value: "NIDERA: TRIGO | BAGUETTE 9"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE PREMIUM 11" , value: "NIDERA: TRIGO | BAGUETTE PREMIUM 11"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE PREMIUM 13" , value: "NIDERA: TRIGO | BAGUETTE PREMIUM 13"},
{obtentor:'NIDERA',Cultivo: "TRIGO" , variedad: "BAGUETTE SUR 5" , value: "NIDERA: TRIGO | BAGUETTE SUR 5"},
{obtentor:'RAGT',Cultivo: "TRIGO" , variedad: "RGT QUIRIKO" , value: "RAGT: TRIGO | RGT QUIRIKO"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "ALHAMBRA" , value: "SURSEM: TRIGO | ALHAMBRA"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "ARPLUS" , value: "SURSEM: TRIGO | ARPLUS"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "ATHORIS" , value: "SURSEM: TRIGO | ATHORIS"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "AVISO" , value: "SURSEM: TRIGO | AVISO"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "CALDEN" , value: "SURSEM: TRIGO | CALDEN"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "CENTINELA" , value: "SURSEM: TRIGO | CENTINELA"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "CH 12576" , value: "SURSEM: TRIGO | CH 12576"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "CH 13338" , value: "SURSEM: TRIGO | CH 13338"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "CORIOLIS" , value: "SURSEM: TRIGO | CORIOLIS"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "FABULIS" , value: "SURSEM: TRIGO | FABULIS"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "LAPACHO" , value: "SURSEM: TRIGO | LAPACHO"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "LE 2271" , value: "SURSEM: TRIGO | LE 2271"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "LE 2294" , value: "SURSEM: TRIGO | LE 2294"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "LE 2330" , value: "SURSEM: TRIGO | LE 2330"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "LE 2331" , value: "SURSEM: TRIGO | LE 2331"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "LE 2333" , value: "SURSEM: TRIGO | LE 2333"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "LE 2341" , value: "SURSEM: TRIGO | LE 2341"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "LG ARLASK" , value: "SURSEM: TRIGO | LG ARLASK"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "LG ARYAL" , value: "SURSEM: TRIGO | LG ARYAL"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "LG MORO" , value: "SURSEM: TRIGO | LG MORO"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "LG ZAINO" , value: "SURSEM: TRIGO | LG ZAINO"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "LGWA11-0169" , value: "SURSEM: TRIGO | LGWA11-0169"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "LIMAY" , value: "SURSEM: TRIGO | LIMAY"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "SIRIRI" , value: "SURSEM: TRIGO | SIRIRI"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "SN 90" , value: "SURSEM: TRIGO | SN 90"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "SRM NOGAL" , value: "SURSEM: TRIGO | SRM NOGAL"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "VIRGILE" , value: "SURSEM: TRIGO | VIRGILE"},
{obtentor:'SURSEM',Cultivo: "TRIGO" , variedad: "ZORZAL" , value: "SURSEM: TRIGO | ZORZAL"}          
            ],
            optionGroupRegister: function (optgroup) {
              var capitalised = optgroup.charAt(0).toUpperCase() + optgroup.substring(1);
              var group = {
                label: 'Obtentor: ' + capitalised
              };

              group[this.settings.optgroupValueField] = optgroup;

              return group;
            },
            render: {
              item: function (item, escape) {
                  return (
                  "<div>" +
                  (item.variedad
                      ? '<span class="name">' + escape(item.variedad) + "</span>"
                      : "") +
                  "</div>"
                  );
              },
              option: function (item, escape) {
                  var label = item.variedad;
                  var caption = item.cultivo;
                  return (
                  "<div style='display: flex; justify-content: space-between; padding: 2px 4px'>" +
                  '<span class="label">' +
                  escape(label) +
                  "</span>" +
                  (caption
                      ? '<span class="caption">' + escape(caption) + "</span>"
                      : "") +
                  "</div>"
                  );
              },
            },
            placeholder: 'Click here to select ...',
            optgroupField: 'obtentor',
            labelField: 'variedad',
            searchField: ['variedad', 'obtentor', 'cultivo'],
            sortField: 'variedad'
          });
      }

      obtentores(jQuery('.wpcf7-field-group').find("[name^='obtentor']")[0])

      jQuery('form.wpcf7-form').on('DOMNodeInserted', '.wpcf7-field-group', function (ele) {

            console.log('added')
            
            obtentores(jQuery(ele.currentTarget).find("[name^='obtentor']")[0])
            
      });
       
    });
    

});



